language: python
dist: xenial
cache: pip

branches:
  only:
  - master
  - /^v(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/ # SemVer tags (https://github.com/semver/semver/issues/232#issuecomment-405596809)

env:
  global:
    - VERMOUTH_TEST_DSSP=mkdssp
    - SKIP_GENERATE_AUTHORS=1
    - SKIP_WRITE_GIT_CHANGELOG=1
  matrix:
    - WITH_SCIPY=true WITH_CODECOV=true
before_install:
  - pip install --upgrade setuptools pip
install:
  - if [[ ${WITH_SCIPY} == true ]]; then pip install scipy; fi
  - pip install --upgrade .
before_script:
  - pip install --upgrade -r requirements-tests.txt
script:
  - coverage run --source=vermouth $(which pytest) -vv vermouth --hypothesis-show-statistics
after_success:
  - coverage report --omit='*/bin/pytest'
  - if [[ ${WITH_CODECOV} == true ]]; then codecov; fi
addons:
  apt:
    packages:
     - dssp

jobs:
  fast_finish: true
  allow_failures:
    #- python: "2.7"
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"
  include:
      #- python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"
      env: WITH_SCIPY=false WITH_CODECOV=false

    - stage: docs
      python: "3.7"
      addons: skip
      install:
        - pip install --upgrade -r requirements-docs.txt
        - pip install --upgrade .[full]
      # script: python setup.py build_sphinx
      script: mkdir -p doc/source/_static; sphinx-build -EnW -b html doc/source/ doc/build/html
      after_success: skip

    - stage: pylint
      python: "3.7"
      addons: skip
      install:
        - pip install --upgrade -r requirements-tests.txt
        - pip install pylint
      script:
        - python run_pylint.py --disable=fixme --fail-under=9 vermouth
        - python run_pylint.py --disable=fixme --fail-under=9.5 bin/martinize2
      after_success: skip

    - stage: deploy
      python: "3.7"
      addons: skip
      env: WITH_CODECOV=false
      before_script: skip
      script: skip
      deploy:
          provider: pypi
          user: pckroon
          password:
              # travis encrypt --add deploy.password
              secure: "Wc4fsA5ADWlAp7oiRk+QhR3H3UtqjHHg16pn3GoCRE2JQZM97uzt0Db6pCUxGiQAG9bq70LJG2D10OVl3GFjmy2aQnGE1XgleJuYWU4rpxQ4YPAQZzHqcdTY/KnDQSfSoMoeZFpqgNq5sq1Kt2nGmEco6F6sy1o8p6FoD5wI5HVSzUyd7xBPYVgIwd8//OAgbPypTqC+MwqSNbaVw/jABlknfQqmZpFBC0MpRCa5/MMixNDEL8cNNjT+0g/yHHzi5KKFY/KNOMuG5PJ4ztwEVIg/ExwaulM4RrWGUaYScI8Uj9H6ncfYdu+ldgJuMzQHV2EQ3X1+4k2tgPOCleLg+S936MN4b6D9s97PiUxAsr182s04t+Rypdrlag+UU4YTSsCA3GF2aX4tk1RT5rAiWvyMQquy+s2QN6El+IsCWrq1stgxihvLXiELe/MZJexsmQ3sTb/BcVr5govnGSxOlCyE+4DUkIIBw2W9KpaJrue2jrwE71dyG4nHyLAjRjKl01glJysv9zlqH37W0RstutaT9JtaVg58N4Ot/Emh7whWpWcdaiBAmR5VfdMgMbuWTNF7qSaluE0fbnXH2HbbbFwOPehJnv8kMyibEKK0kt60fb8/nDjcp7v4n5EqO4ENm/0MhPnBFt4wFObkzb5Bq8snznqYd70sFqumut4HV1Y="
          on:
              tags: true
 
